### ISSUE TITLE
Cannot find module '../src/greeterNode'​​

### ISSUE THREAD

**Issue by zeroEvidence** [wallabyjs/wallaby-typescript-sample#3]
Using VS Code.
Cloned your repo, npm i, select config 'wallaby-node.js', start.
Error in console: 

```
​​​​​0 failing tests, 0 passing​​​​​
​​​​​​​​​​
​​Error: Cannot find module '../src/greeterNode'​​
  at ​test/greeterNodeSpec.ts:3​
```

**Comment by ArtemGovorov** [comment]
Thanks for reporting it, it was the [incorrect module setting in the `tsconfig.json`](https://github.com/wallabyjs/wallaby-typescript-sample/commit/04c1fc862b4d2ec2e1391b37646095451021c491), fixed now.
