### ISSUE TITLE
Aliases in Wallaby.js without webpack?

### ISSUE THREAD

**Issue by ThatSpaceGuy** [wallabyjs/wallaby-typescript-sample#5]
Hello, I've seen your answer about aliases in Wallaby.js using webpack (https://github.com/wallabyjs/ngCliWebpackSample/issues/30).  Is it possible to resolve aliases without webpack?  I'm attempting to run wallaby.js using `type: 'node'` and `kind: 'chrome'`.

**Comment by smcenlly** [comment]
Yes, this is possible. You need to update your wallaby.js file to resolve the paths. Details of how to set up are on our [typescript documentation](https://wallabyjs.com/docs/integration/typescript.html#typescript-compileroptionspaths-setting) page. I've also pasted below for your convenience:

1. Include tsconfig.json in your file list.
2. Ensure that your project includes the tsconfig-paths package.
3. Add a wallaby setup configuration function to register your paths.

```javascript
module.exports = function () {

  return {
    files: [
      'tsconfig.json',
      ...
    ],

    ...

    setup: function (wallaby) {
      if (global._tsconfigPathsRegistered) return;
      const tsConfigPaths = require('tsconfig-paths');
      const tsconfig = require('./tsconfig.json');
      tsConfigPaths.register({
        baseUrl: tsconfig.compilerOptions.baseUrl,
        paths: tsconfig.compilerOptions.paths
      });
      global._tsconfigPathsRegistered = true;
    }
  };
};
```

**Comment by kutenai** [comment]
So, this is a great response -- if you are using Typescript. I'm using React with Babel, but not using typescript. The above solution seems very tied to typescript. 

I also have the Quokka tool, which includes a plugin and the ability to directly support aliases, which works great.. can that sort of capability be used in Wallaby???

**Comment by smcenlly** [comment]
Does the [babel-plugin-webpack-alias](https://www.npmjs.com/package/babel-plugin-webpack-alias) package or [module-alias](https://www.npmjs.com/package/module-alias) package give you what you're after?

We recommend finding a package to do this, but it is possible to build your own. Depending on how the package works, you may need to load it in the wallaby `setup` function.

If you can't find a package to do this, you could implement this yourself by duck punching Module._resolveFilename() in the `setup` function in your `wallaby.conf.js` file. I took the core logic from [tsconfig-paths register.ts](https://github.com/dividab/tsconfig-paths/blob/master/src/register.ts) function to provide an example of how to do this (see below). This hard-coded example would allow you to require `const b = require('@b');` in a file that resolves to `../src/b.js`.

```javascript
module.exports = function () {
    return {
      files: [
        'src/**/*.js'
      ],
  
      tests: [
        'test/**/*spec.js'
      ],
  
      env: {
        type: 'node'
      },

      testFramework: 'jasmine',

      setup: function(wallaby) {
        const Module = require("module");
        const originalResolveFilename = Module._resolveFilename;
        Module._resolveFilename = function(request, _parent) {
            if (request == '@b') {
              const found = '../src/b.js'; // NOTE: prod implementation would need this to resolve to an absolute path
              if (found) {
                const modifiedArguments = [found, ...[].slice.call(arguments, 1)]; // Passes all arguments. Even those that is not specified above.
                return originalResolveFilename.apply(this, modifiedArguments);
              }
            }
            return originalResolveFilename.apply(this, arguments);
          };
      }
    };
  };
```
